name: Deploy Horror Player

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # This step gathers your files for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Change this path if your files are inside a subfolder
          path: '.' 

      # This step sends the package to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
